service: serverless-data-operation
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  dataoperations:
    handler: handler.dataoperations
    events:
      - http:
          path: /
          method: post

resources:
  Resources:
    Dataformtable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: data-form
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: N
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 3
            WriteCapacityUnits: 3
