service: serverless-data-operation
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/data-form"

functions:
  dataoperations:
    handler: handler.dataoperations
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  Resources:
    Dataformtable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: data-form
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: N
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 3
            WriteCapacityUnits: 3
